### ISSUE TITLE
sqlite3 error when trying to run `beame-gatekeeper server start`

### ISSUE THREAD

**Issue by Jasonb11** [beameio/beame-gatekeeper#7]
`root@raspberrypi-1:~/.beame_server/creds# beame-gatekeeper server start
[2017-06-11 12:55:23] [Bootstrapper] INFO: Beame-gatekeeper config files ensured
[2017-06-11 12:55:31] [Bootstrapper] ERROR: Error: Command failed: /usr/local/lib/node_modules/beame-gatekeeper/node_modules/.bin/sequelize db:migrate --migrations-path /usr/local/lib/node_modules/beame-gatekeeper/migrations --seeders-path /usr/local/lib/node_modules/beame-gatekeeper/seeders --models-path /usr/local/lib/node_modules/beame-gatekeeper/models --env production --config /root/.beame_server/config/sqlite_config.json
[2017-06-11 12:55:31] [Bootstrapper] ERROR: Error: Please install sqlite3 package manually
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at new ConnectionManager (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at new SqliteDialect (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at new Sequelize (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize/lib/sequelize.js:233:18)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at getSequelizeInstance (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize-cli/lib/tasks/db.js:385:12)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at getMigrator (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize-cli/lib/tasks/db.js:394:21)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Object.task (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize-cli/lib/tasks/db.js:24:14)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at /usr/local/lib/node_modules/beame-gatekeeper/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at tryCatcher (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/util.js:16:23)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/promise.js:512:31)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Promise._settlePromise (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/promise.js:569:18)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Promise._settlePromise0 (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/promise.js:614:10)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Promise._settlePromises (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/promise.js:693:18)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Async._drainQueue (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/async.js:133:16)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Async._drainQueues (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/async.js:143:10)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/beame-gatekeeper/node_modules/bluebird/js/release/async.js:17:14)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at runCallback (timers.js:672:20)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at ChildProcess.exithandler (child_process.js:204:12)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at emitTwo (events.js:106:13)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at ChildProcess.emit (events.js:191:7)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at maybeClose (internal/child_process.js:891:16)
[2017-06-11 12:55:31] [Bootstrapper] ERROR:     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
`

What could be causing this issue? I'm not sure how to install sqlite3 manually as the error suggests.

**Comment by ilyash** [comment]
Please try the following:

* `cd /usr/local/lib/node_modules/beame-gatekeeper/ && sudo npm rebuild` then try to re-run `beame-gatekeeper server start`
* if the above does not help, `sudo npm uninstall -g beame-gatekeeper && npm install -g --unsafe-perm beame-gatekeeper` then re-run `beame-gatekeeper server start`

**Comment by Jasonb11** [comment]
maybe i should have said the correct issue when starting this issue...

I am having trouble with the Token being recognized.

![2017-06-11 15_30_47-](https://user-images.githubusercontent.com/14957568/27013914-1ee5c32c-4ebb-11e7-92d1-6c89b78b9af2.png)

**Comment by AlexzxelA** [comment]
Registration token has limited lifetime. Can you try with a new one? You can get it as usual from start.beameio.net

**Comment by zglozman** [comment]
It could be that, or it could be you time on the raspberry pi, pls check that date & time are correctly set. 
Crypto relies on somewhat accurate time stamps.

**Comment by Jasonb11** [comment]
my time is correct:
root@raspberrypi-1:/usr/local/lib/node_modules# date
Sun Jun 11 16:10:48 EDT 2017

i tried with a newly created cred and it still does't work api error..

**Comment by zglozman** [comment]
I have suggestion: Install it as a system-demon using the install script, you launch it 
beame-gatekeeper-install-systemd 'token'

this will accomplish a number of things, mainly install all of this under a different user.

and automatically start, run this command,and let me know,

**Comment by Jasonb11** [comment]
maybe the issue is that I have a beame service already running from a startup script in rc.local to initialize beame-insta-ssl...

**Comment by zglozman** [comment]
I know why. There is a conflict with the beame-sdk.



To fix npm update -g beame-sk
Npm update -g beame-insta-ssk

Let me know the outcome

**Comment by Jasonb11** [comment]
i think some of those commands you just stated are incorrect.
*beame-sdk
*beame-insta-ssl

**Comment by Jasonb11** [comment]
--fqdn parameter is required because you have more than one certificate

im not sure what this means.. I have signed up for 4 creds. Some of them may have been verified some might not. They are all installed on the same raspberry pi. I want to start multiple tunnels for various servers that are running some iot devices. (mostly other raspberry pis)

**Comment by zglozman** [comment]
Sorry I typed it on my iPhone. Yes there should be no problem to host multiple credentials.  The way to do this is is with the gatekeeper. 

I see from my end that the gatekeeper got its credentials. If you installed it as system-demon which is what i suggested, it would not be a problem.

To find out which fqdn's you have you type beame-insta-ssl creds list 

In beame system's credentials are organized into logic trees. 
	fn1bzdwqd64y4toz.v1.p.beameio.net

You can see which credentials you have by calling 'beame creds list' or beame-insta-ssl creds list 

You should have 2 l0 credentials 
L0 means that there is only XXXXXX.beameio.net, and not yyyy.xxx.beameio.net 

But you should not have to use the beame-insta-SSL at all, what you should do instead, is 
A. Install the gatekeeper as a systemd service. 
B. Download iOS app, (sorry android not yet availibale) 
C.  Get the admin token to the gatekeeper using the 'beame-gatekeeper-ctl admin' command 
D. Go to the services tab and define all  the applications you need. 
E. Logout
F. Go to the gatekeeper URL beame-gatekeeper-ctl info,  and register with your mobile. 


To save us both a bunch time and typing checkout this playlist it should really be everything you need.
In any case if you want me to walk you through it, contact me on email and we will just talk live. M
Z@beame.io

**Comment by ilyash** [comment]
I have tried to switch to some more productive communication channel using email `b********1@g***l.com` but got no reply.

**Comment by ilyash** [comment]
After some private communication, the issue was postponed. Closing due to inactivity. Please feel free to re-open.
